name: janus-gateway

# Local Dockerfile
env:
  context: janus-gateway
  dockerfile: janus-gateway/Dockerfile
  dest_repo:  ghcr.io/lnobach/janus-gateway
  dest_tag: 0.12.2

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Check if image already built
        run: set +e; docker manifest inspect $dest_repo:$dest_tag > /dev/null; echo "image_exists=$?" >> $GITHUB_ENV
      - name: Build and push
        if: env.image_exists == 1
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.context }}
          file: ${{ env.dockerfile }}
          push: true
          tags: ${{ env.dest_repo }}:${{ env.dest_tag }}
